import type { Metadata } from 'next';
import { Inter, Open_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import TanstackProvider from '@/providers/TanstackProvider';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';

const helvetica = localFont({ src: '../fonts/Helvetica.woff2' });
const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackProvider>
        <body className={`${helvetica.className} antialiased`}>
          <div className=" container px-[24px] pt-[10px] md:px-[40px] md:pt-[16px]">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </TanstackProvider>
    </html>
  );
}
